logging.level:
  todoapp: DEBUG
  org.springframework.boot: INFO
  org.springframework.web: DEBUG
  
sitee:
  author: icarus
  features:
    auth: true
  
spring:
  http:
    encoding:
      force: true